0;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Model;name;de.mdelab.migmm.sample.git.hello#
1;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;de#proxy;false#
2;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;java#proxy;true#
3;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeInt;name;int#proxy;false#
4;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeLong;name;long#proxy;false#
5;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeFloat;name;float#proxy;false#
6;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeDouble;name;double#proxy;false#
7;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeBoolean;name;boolean#proxy;false#
8;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeVoid;name;void#proxy;false#
9;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeChar;name;char#proxy;false#
10;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeShort;name;short#proxy;false#
11;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeByte;name;byte#proxy;false#
12;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ArrayType;name;java.lang.String[]#proxy;false#dimensions;1#
13;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;CompilationUnit;name;HelloWorld.java#proxy;false#originalFilePath;Y:\sample_repos\hello\de.mdelab.migmm.sample.git.hello\src\de\mdelab\migmm\sample\git\hello\HelloWorld.java#
14;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;CompilationUnit;name;Greeter.java#proxy;false#originalFilePath;Y:\sample_repos\hello\de.mdelab.migmm.sample.git.hello\src\de\mdelab\migmm\sample\git\hello\Greeter.java#
15;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;mdelab#proxy;false#
16;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;lang#proxy;true#
17;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;io#proxy;true#
18;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
19;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
20;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
21;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
22;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
23;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
24;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;hello#proxy;false#
25;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ClassDeclaration;name;HelloWorld#proxy;false#
26;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ImportDeclaration;static;false#
27;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ClassDeclaration;name;Greeter#proxy;false#
28;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;migmm#proxy;false#
29;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ClassDeclaration;name;String#proxy;true#
30;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;Comparable#proxy;true#
31;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;CharSequence#proxy;true#
32;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;AutoCloseable#proxy;true#
33;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;Appendable#proxy;true#
34;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ClassDeclaration;name;System#proxy;true#
35;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;constant#proxy;true#
36;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;Serializable#proxy;true#
37;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ClassDeclaration;name;PrintStream#proxy;true#
38;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ClassDeclaration;name;FilterOutputStream#proxy;true#
39;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ClassDeclaration;name;OutputStream#proxy;true#
40;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;Closeable#proxy;true#
41;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;Flushable#proxy;true#
42;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;git#proxy;false#
43;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;public#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
44;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
45;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
46;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;FieldDeclaration;proxy;false#
47;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ConstructorDeclaration;name;HelloWorld#proxy;false#
48;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodDeclaration;name;greet#proxy;false#extraArrayDimensions;0#
49;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodDeclaration;name;main#proxy;false#extraArrayDimensions;0#
50;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;public#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
51;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
52;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
53;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;FieldDeclaration;proxy;false#
54;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ConstructorDeclaration;name;Greeter#proxy;false#
55;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodDeclaration;name;greet#proxy;false#extraArrayDimensions;0#
56;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodDeclaration;name;getPrintStream#proxy;false#extraArrayDimensions;0#
57;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodDeclaration;name;print#proxy;false#extraArrayDimensions;0#
58;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodDeclaration;name;getMessage#proxy;false#extraArrayDimensions;0#
59;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;sample#proxy;false#
60;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
61;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
62;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
63;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
64;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
65;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
66;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
67;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
68;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
69;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
70;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
71;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
72;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
73;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
74;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
75;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeParameter;name;T#proxy;true#
76;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
77;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
78;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
79;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;FieldDeclaration;proxy;true#
80;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;Constable#proxy;true#
81;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;ConstantDesc#proxy;true#
82;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
83;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
84;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodDeclaration;name;print#proxy;true#extraArrayDimensions;0#
85;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
86;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
87;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
88;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
89;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
90;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;private#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
91;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;VariableDeclarationFragment;name;greeter#proxy;false#extraArrayDimensions;0#
92;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;public#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
93;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Block;
94;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableDeclaration;name;greeting#proxy;false#extraArrayDimensions;0#varargs;false#
95;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ClassInstanceCreation;
96;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;public#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
97;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Block;
98;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableDeclaration;name;name#proxy;false#extraArrayDimensions;0#varargs;false#
99;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodInvocation;
100;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;public#inheritance;none#static;true#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
101;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Block;
102;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableDeclaration;name;args#proxy;false#extraArrayDimensions;0#varargs;false#
103;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;private#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
104;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;VariableDeclarationFragment;name;greeting#proxy;false#extraArrayDimensions;0#
105;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;public#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
106;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Block;
107;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableDeclaration;name;greeting#proxy;false#extraArrayDimensions;0#varargs;false#
108;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ClassInstanceCreation;
109;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;public#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
110;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Block;
111;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableDeclaration;name;name#proxy;false#extraArrayDimensions;0#varargs;false#
112;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodInvocation;
113;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;private#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
114;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Block;
115;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodInvocation;
116;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;private#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
117;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Block;
118;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableDeclaration;name;message#proxy;false#extraArrayDimensions;0#varargs;false#
119;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableDeclaration;name;out#proxy;false#extraArrayDimensions;0#varargs;false#
120;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodInvocation;
121;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;private#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
122;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Block;
123;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableDeclaration;name;name#proxy;false#extraArrayDimensions;0#varargs;false#
124;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodInvocation;
125;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;VariableDeclarationFragment;name;out#proxy;true#extraArrayDimensions;0#
126;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableDeclaration;name;arg0#proxy;true#extraArrayDimensions;0#varargs;false#
127;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodInvocation;
128;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
129;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
130;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ExpressionStatement;
131;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
132;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
133;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;StringLiteral;escapedValue;"Hello"#
134;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ExpressionStatement;
135;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
136;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
137;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;StringLiteral;escapedValue;"Alex"#
138;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
139;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;VariableDeclarationStatement;extraArrayDimensions;0#
140;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ExpressionStatement;
141;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
142;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
143;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
144;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ExpressionStatement;
145;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
146;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
147;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;VariableDeclarationStatement;extraArrayDimensions;0#
148;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ExpressionStatement;
149;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
150;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
151;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ReturnStatement;
152;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ExpressionStatement;
153;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
154;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
155;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
156;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
157;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
158;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ReturnStatement;
159;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
160;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
161;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
162;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Assignment;operator;ASSIGN#
163;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;VariableDeclarationFragment;name;hello#proxy;false#extraArrayDimensions;0#
164;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
165;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Assignment;operator;ASSIGN#
166;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;VariableDeclarationFragment;name;message#proxy;false#extraArrayDimensions;0#
167;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
168;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InfixExpression;operator;PLUS#
169;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;FieldAccess;
170;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;FieldAccess;
171;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;StringLiteral;escapedValue;" "#
172;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ThisExpression;
173;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ThisExpression;
===========
0;ownedElements;1
0;ownedElements;2
0;orphanTypes;3
0;orphanTypes;4
0;orphanTypes;5
0;orphanTypes;6
0;orphanTypes;7
0;orphanTypes;8
0;orphanTypes;9
0;orphanTypes;10
0;orphanTypes;11
0;orphanTypes;12
0;compilationUnits;13
0;compilationUnits;14
1;ownedPackages;15
2;ownedPackages;16
2;ownedPackages;17
8;usagesInTypeAccess;18
8;usagesInTypeAccess;19
8;usagesInTypeAccess;20
8;usagesInTypeAccess;21
12;usagesInTypeAccess;22
12;elementType;23
13;package;24
13;types;25
14;imports;26
14;package;24
14;types;27
15;ownedPackages;28
16;ownedElements;29
16;ownedElements;30
16;ownedElements;31
16;ownedElements;32
16;ownedElements;33
16;ownedElements;34
16;ownedPackages;35
17;ownedElements;36
17;ownedElements;37
17;ownedElements;38
17;ownedElements;39
17;ownedElements;40
17;ownedElements;41
23;type;29
24;ownedElements;25
24;ownedElements;27
24;package;42
25;originalCompilationUnit;13
25;modifier;43
25;usagesInTypeAccess;44
25;usagesInTypeAccess;45
25;bodyDeclarations;46
25;bodyDeclarations;47
25;bodyDeclarations;48
25;bodyDeclarations;49
26;originalCompilationUnit;14
26;importedElement;37
27;originalCompilationUnit;14
27;modifier;50
27;usagesInTypeAccess;51
27;usagesInTypeAccess;52
27;bodyDeclarations;53
27;bodyDeclarations;54
27;bodyDeclarations;55
27;bodyDeclarations;56
27;bodyDeclarations;57
27;bodyDeclarations;58
28;ownedPackages;59
29;usagesInTypeAccess;60
29;usagesInTypeAccess;61
29;usagesInTypeAccess;62
29;usagesInTypeAccess;63
29;usagesInTypeAccess;64
29;usagesInTypeAccess;65
29;usagesInTypeAccess;66
29;usagesInTypeAccess;67
29;usagesInTypeAccess;68
29;usagesInTypeAccess;69
29;superInterfaces;70
29;superInterfaces;71
29;superInterfaces;72
29;superInterfaces;73
29;superInterfaces;74
30;usagesInTypeAccess;71
30;typeParameters;75
31;usagesInTypeAccess;72
32;usagesInTypeAccess;76
33;usagesInTypeAccess;77
34;usagesInTypeAccess;78
34;bodyDeclarations;79
35;ownedElements;80
35;ownedElements;81
36;usagesInTypeAccess;70
37;usagesInTypeAccess;82
37;usagesInTypeAccess;83
37;bodyDeclarations;84
37;superInterfaces;77
37;superInterfaces;85
37;superClass;86
38;usagesInTypeAccess;86
38;superClass;87
39;usagesInTypeAccess;87
39;superInterfaces;88
39;superInterfaces;89
40;usagesInTypeAccess;88
40;usagesInTypeAccess;85
40;superInterfaces;76
41;usagesInTypeAccess;89
42;package;59
46;originalCompilationUnit;13
46;modifier;90
46;type;51
46;fragments;91
47;originalCompilationUnit;13
47;modifier;92
47;body;93
47;parameters;94
47;usages;95
48;originalCompilationUnit;13
48;modifier;96
48;body;97
48;parameters;98
48;usages;99
48;returnType;18
49;originalCompilationUnit;13
49;modifier;100
49;body;101
49;parameters;102
49;returnType;19
53;originalCompilationUnit;14
53;modifier;103
53;type;62
53;fragments;104
54;originalCompilationUnit;14
54;modifier;105
54;body;106
54;parameters;107
54;usages;108
55;originalCompilationUnit;14
55;modifier;109
55;body;110
55;parameters;111
55;usages;112
55;returnType;20
56;originalCompilationUnit;14
56;modifier;113
56;body;114
56;usages;115
56;returnType;82
57;originalCompilationUnit;14
57;modifier;116
57;body;117
57;parameters;118
57;parameters;119
57;usages;120
57;returnType;21
58;originalCompilationUnit;14
58;modifier;121
58;body;122
58;parameters;123
58;usages;124
58;returnType;68
73;type;80
74;type;81
79;fragments;125
84;parameters;126
84;usages;127
91;originalCompilationUnit;13
91;usageInVariableAccess;128
91;usageInVariableAccess;129
93;originalCompilationUnit;13
93;statements;130
94;originalCompilationUnit;13
94;usageInVariableAccess;131
94;modifier;132
94;type;60
95;originalCompilationUnit;13
95;arguments;133
95;type;45
97;originalCompilationUnit;13
97;statements;134
98;originalCompilationUnit;13
98;usageInVariableAccess;135
98;modifier;136
98;type;61
99;originalCompilationUnit;13
99;arguments;137
99;expression;138
101;originalCompilationUnit;13
101;statements;139
101;statements;140
102;originalCompilationUnit;13
102;modifier;141
102;type;22
104;originalCompilationUnit;14
104;usageInVariableAccess;142
104;usageInVariableAccess;143
106;originalCompilationUnit;14
106;statements;144
107;originalCompilationUnit;14
107;usageInVariableAccess;145
107;modifier;146
107;type;63
108;originalCompilationUnit;13
108;arguments;131
108;type;52
110;originalCompilationUnit;14
110;statements;147
110;statements;148
111;originalCompilationUnit;14
111;usageInVariableAccess;149
111;modifier;150
111;type;64
112;originalCompilationUnit;13
112;arguments;135
112;expression;129
114;originalCompilationUnit;14
114;statements;151
115;originalCompilationUnit;14
117;originalCompilationUnit;14
117;statements;152
118;originalCompilationUnit;14
118;usageInVariableAccess;153
118;modifier;154
118;type;66
119;originalCompilationUnit;14
119;usageInVariableAccess;155
119;modifier;156
119;type;83
120;originalCompilationUnit;14
120;arguments;157
120;arguments;115
122;originalCompilationUnit;14
122;statements;158
123;originalCompilationUnit;14
123;usageInVariableAccess;159
123;modifier;160
123;type;69
124;originalCompilationUnit;14
124;arguments;149
125;usageInVariableAccess;161
126;type;67
127;originalCompilationUnit;14
127;arguments;153
127;expression;155
130;originalCompilationUnit;13
130;expression;162
133;originalCompilationUnit;13
134;originalCompilationUnit;13
134;expression;112
137;originalCompilationUnit;13
138;variable;163
139;originalCompilationUnit;13
139;type;44
139;fragments;163
139;modifier;164
140;originalCompilationUnit;13
140;expression;99
144;originalCompilationUnit;14
144;expression;165
147;originalCompilationUnit;14
147;type;65
147;fragments;166
147;modifier;167
148;originalCompilationUnit;14
148;expression;120
151;originalCompilationUnit;14
151;expression;161
152;originalCompilationUnit;14
152;expression;127
157;variable;166
158;originalCompilationUnit;14
158;expression;168
161;qualifier;78
162;originalCompilationUnit;13
162;leftHandSide;169
162;rightHandSide;108
163;originalCompilationUnit;13
163;initializer;95
165;originalCompilationUnit;14
165;leftHandSide;170
165;rightHandSide;145
166;originalCompilationUnit;14
166;initializer;124
168;originalCompilationUnit;14
168;rightOperand;171
168;leftOperand;143
168;extendedOperands;159
169;originalCompilationUnit;13
169;field;128
169;expression;172
170;originalCompilationUnit;14
170;field;142
170;expression;173
171;originalCompilationUnit;14
172;originalCompilationUnit;13
173;originalCompilationUnit;14
