0;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Model;name;de.mdelab.migmm.sample.git.hello#
1;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;de#proxy;false#
2;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;java#proxy;true#
3;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeInt;name;int#proxy;false#
4;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeLong;name;long#proxy;false#
5;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeFloat;name;float#proxy;false#
6;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeDouble;name;double#proxy;false#
7;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeBoolean;name;boolean#proxy;false#
8;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeVoid;name;void#proxy;false#
9;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeChar;name;char#proxy;false#
10;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeShort;name;short#proxy;false#
11;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;PrimitiveTypeByte;name;byte#proxy;false#
12;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ArrayType;name;java.lang.String[]#proxy;false#dimensions;1#
13;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;CompilationUnit;name;HelloWorld.java#proxy;false#originalFilePath;Y:\sample_repos\hello\de.mdelab.migmm.sample.git.hello\src\de\mdelab\migmm\sample\git\hello\HelloWorld.java#
14;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;mdelab#proxy;false#
15;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;io#proxy;true#
16;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;lang#proxy;true#
17;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
18;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
19;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
20;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
21;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
22;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ImportDeclaration;static;false#
23;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;hello#proxy;false#
24;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ClassDeclaration;name;HelloWorld#proxy;false#
25;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;migmm#proxy;false#
26;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ClassDeclaration;name;PrintStream#proxy;true#
27;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ClassDeclaration;name;FilterOutputStream#proxy;true#
28;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ClassDeclaration;name;OutputStream#proxy;true#
29;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;Closeable#proxy;true#
30;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;Flushable#proxy;true#
31;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;Serializable#proxy;true#
32;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;AutoCloseable#proxy;true#
33;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;Appendable#proxy;true#
34;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ClassDeclaration;name;String#proxy;true#
35;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;Comparable#proxy;true#
36;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;CharSequence#proxy;true#
37;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ClassDeclaration;name;System#proxy;true#
38;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;constant#proxy;true#
39;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;git#proxy;false#
40;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;public#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
41;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
42;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
43;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;FieldDeclaration;proxy;false#
44;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ConstructorDeclaration;name;HelloWorld#proxy;false#
45;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodDeclaration;name;greet#proxy;false#extraArrayDimensions;0#
46;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodDeclaration;name;print#proxy;false#extraArrayDimensions;0#
47;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodDeclaration;name;getMessage#proxy;false#extraArrayDimensions;0#
48;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodDeclaration;name;main#proxy;false#extraArrayDimensions;0#
49;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Package;name;sample#proxy;false#
50;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
51;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodDeclaration;name;print#proxy;true#extraArrayDimensions;0#
52;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
53;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
54;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
55;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
56;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
57;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
58;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
59;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
60;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
61;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
62;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
63;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
64;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
65;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
66;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
67;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
68;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
69;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
70;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
71;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
72;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeParameter;name;T#proxy;true#
73;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;TypeAccess;
74;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;FieldDeclaration;proxy;true#
75;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;Constable#proxy;true#
76;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InterfaceDeclaration;name;ConstantDesc#proxy;true#
77;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;private#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
78;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;VariableDeclarationFragment;name;greeting#proxy;false#extraArrayDimensions;0#
79;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;public#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
80;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Block;
81;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableDeclaration;name;greeting#proxy;false#extraArrayDimensions;0#varargs;false#
82;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ClassInstanceCreation;
83;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;public#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
84;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Block;
85;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableDeclaration;name;name#proxy;false#extraArrayDimensions;0#varargs;false#
86;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodInvocation;
87;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;private#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
88;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Block;
89;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableDeclaration;name;message#proxy;false#extraArrayDimensions;0#varargs;false#
90;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableDeclaration;name;out#proxy;false#extraArrayDimensions;0#varargs;false#
91;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodInvocation;
92;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;private#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
93;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Block;
94;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableDeclaration;name;name#proxy;false#extraArrayDimensions;0#varargs;false#
95;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodInvocation;
96;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;public#inheritance;none#static;true#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
97;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Block;
98;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableDeclaration;name;args#proxy;false#extraArrayDimensions;0#varargs;false#
99;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableDeclaration;name;arg0#proxy;true#extraArrayDimensions;0#varargs;false#
100;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;MethodInvocation;
101;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;VariableDeclarationFragment;name;out#proxy;true#extraArrayDimensions;0#
102;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
103;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
104;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ExpressionStatement;
105;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
106;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
107;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;StringLiteral;escapedValue;"Hello"#
108;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;VariableDeclarationStatement;extraArrayDimensions;0#
109;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ExpressionStatement;
110;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
111;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
112;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;StringLiteral;escapedValue;"Alex"#
113;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
114;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ExpressionStatement;
115;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
116;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
117;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
118;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
119;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
120;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
121;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ReturnStatement;
122;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;SingleVariableAccess;
123;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
124;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;VariableDeclarationStatement;extraArrayDimensions;0#
125;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ExpressionStatement;
126;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
127;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Assignment;operator;ASSIGN#
128;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;VariableDeclarationFragment;name;message#proxy;false#extraArrayDimensions;0#
129;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
130;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;VariableDeclarationFragment;name;hello#proxy;false#extraArrayDimensions;0#
131;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;InfixExpression;operator;PLUS#
132;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;Modifier;visibility;none#inheritance;none#static;false#transient;false#volatile;false#native;false#strictfp;false#synchronized;false#
133;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;FieldAccess;
134;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;StringLiteral;escapedValue;" "#
135;http://www.eclipse.org/MoDisco/Java/0.2.incubation/java;ThisExpression;
===========
0;ownedElements;1
0;ownedElements;2
0;orphanTypes;3
0;orphanTypes;4
0;orphanTypes;5
0;orphanTypes;6
0;orphanTypes;7
0;orphanTypes;8
0;orphanTypes;9
0;orphanTypes;10
0;orphanTypes;11
0;orphanTypes;12
0;compilationUnits;13
1;ownedPackages;14
2;ownedPackages;15
2;ownedPackages;16
8;usagesInTypeAccess;17
8;usagesInTypeAccess;18
8;usagesInTypeAccess;19
12;usagesInTypeAccess;20
12;elementType;21
13;imports;22
13;package;23
13;types;24
14;ownedPackages;25
15;ownedElements;26
15;ownedElements;27
15;ownedElements;28
15;ownedElements;29
15;ownedElements;30
15;ownedElements;31
16;ownedElements;32
16;ownedElements;33
16;ownedElements;34
16;ownedElements;35
16;ownedElements;36
16;ownedElements;37
16;ownedPackages;38
21;type;34
22;originalCompilationUnit;13
22;importedElement;26
23;ownedElements;24
23;package;39
24;originalCompilationUnit;13
24;modifier;40
24;usagesInTypeAccess;41
24;usagesInTypeAccess;42
24;bodyDeclarations;43
24;bodyDeclarations;44
24;bodyDeclarations;45
24;bodyDeclarations;46
24;bodyDeclarations;47
24;bodyDeclarations;48
25;ownedPackages;49
26;usagesInTypeAccess;50
26;bodyDeclarations;51
26;superInterfaces;52
26;superInterfaces;53
26;superClass;54
27;usagesInTypeAccess;54
27;superClass;55
28;usagesInTypeAccess;55
28;superInterfaces;56
28;superInterfaces;57
29;usagesInTypeAccess;56
29;usagesInTypeAccess;53
29;superInterfaces;58
30;usagesInTypeAccess;57
31;usagesInTypeAccess;59
32;usagesInTypeAccess;58
33;usagesInTypeAccess;52
34;usagesInTypeAccess;60
34;usagesInTypeAccess;61
34;usagesInTypeAccess;62
34;usagesInTypeAccess;63
34;usagesInTypeAccess;64
34;usagesInTypeAccess;65
34;usagesInTypeAccess;66
34;usagesInTypeAccess;67
34;superInterfaces;59
34;superInterfaces;68
34;superInterfaces;69
34;superInterfaces;70
34;superInterfaces;71
35;usagesInTypeAccess;68
35;typeParameters;72
36;usagesInTypeAccess;69
37;usagesInTypeAccess;73
37;bodyDeclarations;74
38;ownedElements;75
38;ownedElements;76
39;package;49
43;originalCompilationUnit;13
43;modifier;77
43;type;60
43;fragments;78
44;originalCompilationUnit;13
44;modifier;79
44;body;80
44;parameters;81
44;usages;82
45;originalCompilationUnit;13
45;modifier;83
45;body;84
45;parameters;85
45;usages;86
45;returnType;17
46;originalCompilationUnit;13
46;modifier;87
46;body;88
46;parameters;89
46;parameters;90
46;usages;91
46;returnType;18
47;originalCompilationUnit;13
47;modifier;92
47;body;93
47;parameters;94
47;usages;95
47;returnType;66
48;originalCompilationUnit;13
48;modifier;96
48;body;97
48;parameters;98
48;returnType;19
51;parameters;99
51;usages;100
70;type;75
71;type;76
74;fragments;101
78;originalCompilationUnit;13
78;usageInVariableAccess;102
78;usageInVariableAccess;103
80;originalCompilationUnit;13
80;statements;104
81;originalCompilationUnit;13
81;usageInVariableAccess;105
81;modifier;106
81;type;61
82;originalCompilationUnit;13
82;arguments;107
82;type;42
84;originalCompilationUnit;13
84;statements;108
84;statements;109
85;originalCompilationUnit;13
85;usageInVariableAccess;110
85;modifier;111
85;type;62
86;originalCompilationUnit;13
86;arguments;112
86;expression;113
88;originalCompilationUnit;13
88;statements;114
89;originalCompilationUnit;13
89;usageInVariableAccess;115
89;modifier;116
89;type;64
90;originalCompilationUnit;13
90;usageInVariableAccess;117
90;modifier;118
90;type;50
91;originalCompilationUnit;13
91;arguments;119
91;arguments;120
93;originalCompilationUnit;13
93;statements;121
94;originalCompilationUnit;13
94;usageInVariableAccess;122
94;modifier;123
94;type;67
95;originalCompilationUnit;13
95;arguments;110
97;originalCompilationUnit;13
97;statements;124
97;statements;125
98;originalCompilationUnit;13
98;modifier;126
98;type;20
99;type;65
100;originalCompilationUnit;13
100;arguments;115
100;expression;117
101;usageInVariableAccess;120
104;originalCompilationUnit;13
104;expression;127
107;originalCompilationUnit;13
108;originalCompilationUnit;13
108;type;63
108;fragments;128
108;modifier;129
109;originalCompilationUnit;13
109;expression;91
112;originalCompilationUnit;13
113;variable;130
114;originalCompilationUnit;13
114;expression;100
119;variable;128
120;qualifier;73
121;originalCompilationUnit;13
121;expression;131
124;originalCompilationUnit;13
124;type;41
124;fragments;130
124;modifier;132
125;originalCompilationUnit;13
125;expression;86
127;originalCompilationUnit;13
127;leftHandSide;133
127;rightHandSide;105
128;originalCompilationUnit;13
128;initializer;95
130;originalCompilationUnit;13
130;initializer;82
131;originalCompilationUnit;13
131;rightOperand;134
131;leftOperand;103
131;extendedOperands;122
133;originalCompilationUnit;13
133;field;102
133;expression;135
134;originalCompilationUnit;13
135;originalCompilationUnit;13
